### ISSUE TITLE
 ADD THE SAFER_CHECK ARGUMENT EVERYWHERE

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferTool2#1]
See 
https://github.com/safer-r/ggcute/issues/2

**Comment by Tintin2710** [comment]
codon_finder.R
1. ADD THE SAFER_CHECK ARGUMENT
2. modifié l'ordre

**Comment by Tintin2710** [comment]
permut.R
1. ADD THE SAFER_CHECK ARGUMENT
2. modifié l'ordre

**Comment by Tintin2710** [comment]
slide.R
1. ADD THE SAFER_CHECK ARGUMENT
2. modifié l'ordre

**Comment by Tintin2710** [comment]
trim.R
1. ADD THE SAFER_CHECK ARGUMENT
2. modifié l'ordre
3. complete la partie "required funtions"
